import { empty } from "rxjs";

export const RoutersLink = {
    gettotaldataDelete:"deleteRegisterEvent/",
    gettotaldatagallery:"gettotaldatagallery/",
    gettotaldata:"gettotaldata/",
    assistantDetail:"home/assistantList/assistantDetail/",
    register: "pages/register",
    registerUpdate: "registerUpdate",
    imgUpdate:"imgUpdate",
    registerChallenge:"registerChallenge",
    registerExpoAllies: "registerExpoAllies",
    passwordUpdate:"passwordUpdate",
    home:"/home/dashboard",
    content:"home/content",
    profile:"home/profile",
    login:"pages/login/",
    loginApi:"login",
    forgotPassword:"forgotPassword/",
    city:"city",
    category:"category",
    status:"status/",
    getUsersData:"getUsersData/",
    benefits:"benefits",
    scale:"scale",
    challenges:"challenges",
    customerDetail:"customerDetails/",
    menu:"menu/",
    gettotal:"gettotal?id=",
    createEventosGetfinal:"create_eventos_getfinal?idClientsProjects=",
    getEvent:"create_eventos_getfinal?idClientsProjects=",
    getEventImg:"listRegisterImageEventsList?idClientsProjects=",
    deleteRegisterImageEvent:"deleteRegisterImageEvent/",
    resgisterImageEvents:"resgisterImageEvents",
    residentApplication:"residentApplication",
    emergencyContact:"emergencyContact",
    employers:"employers",
    statu:"status",
    medications:"medications",
    treatment:"treatment",
    registerUsersClients:"register",
    recoveryAgreementPlan:"recoveryAgreementPlan",
    typesOfForms:"typesOfForms",
    generalForms:'generalForms',
    generalFormsList:'generalForms/question',
    authorizationReleaseInformation:"authorizationReleaseInformation",
    phaseUpProgressTracking:"phaseUpProgressTracking",
    phaseUpProgressTrackingTwo:"phaseUpProgressTrackingTwo",
    phaseUpProgressTrackingThree:"phaseUpProgressTrackingThree"
};

export const Menssage = {
    faile: "Please authenticate",
    token:"U2FsdGVkX19YyFaXwKWyOqWfb2dW2AGl0kU85zGTg",
    emptyBolean: false,
    idImg:"No haz agregado una imagen",
    idEvents:"No haz seleccionado un evento",
    nameEvents:"softsaenz",
    nameEventsNull:"No hay datos que descargar",
    passwordAES:"Softsaenz2023*",
    error:"Error",
    tokenlist:"token",
    customerDetail:"customerDetail",
    menu:"menu",
    server:"En la conexión del servidor",
    userValid:"El correo ya se encuentra registrado",
    emailValid:"El Email ingresado no se encuentra registrado",
    businessName: "La razón social es obligatoria",
    identificationCard: "El numero de identificación es obligatorio",
    idCategoryToRegister: "La categoria es obligatoria",
    address: "La dirección es obligatoria",
    phone: "El teléfono es obligatorio",
    idCity: "La ciudad es obligatoria",
    email: "Email is mandatory",
    nit: "El nit no es valido",
    empty: "",
    valiEmail: '^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+$',
    validNumber: /^[1-9]\d{6,10}$/,
    success: "Usuario registrado correctamente",
    successUpdate: "Usuario actualizado correctamente",
    successDelete: "Registro eliminado correctamente",
    successForgot: "Ha tu correo registrado enviamos un link para la recuperación de la contraseña",
    exito:"Exito",
    password: "La contraseña es obligatoria",
    updatePassword: "La contraseña y el correo fueron actualizado correctamente",
    habeas: false,
    habeasDataText:"Debes aceptar las política​ de habeas data",
    personalDataPolicy:"Debes acpetar los términos y condiciones",
    monthlyBudget:"El presupuesto mensual es obligatorio",
    contactPerson:"La persona de contacto es obligatorio",
    successExpo: "El registrado se ralizó correctamente",
    errorPassword: "Passwords are not the same",
    name:"Naame is mandatory",
    surName:"SurName is mandatory",
    documentType:"Document Type is mandatory",
    documentNumber:"Document Number is mandatory",
    sex:"Sex is mandatory",
    birthDate:"Birth Date is mandatory",
    telephone: "Telephone is mandatory",
    passwordClient: "Password is mandatory",
    passwordClientVerify: "Password verify is mandatory"
};